In [27]:
import pandas as pd
import numpy as np
df = pd.read_excel('file/score.xlsx',index_col='지원번호')

In [ ]:
# # NaN데이터 처리 - 결측치(NaN 데이터)
# # fillna : nan데이터 채워줌
# df['SW특기']
# df.fillna('x',inplace=True)



# np.nan : numpy명령어 - nan데이터를 모두 입력
# numpy는 숫자만 가능, 문자가 안됨.
df['학교'] = np.nan
df['학교'] = df['학교'].astype('object')
df.fillna('없음',inplace=True)

       이름  학교    키   국어   영어   수학  과학  사회        SW특기
지원번호
1번    강나래  없음  197   90   85  100  95  85      Python
2번    강태원  없음  184   40   35   50  55  25        Java
3번    강호림  없음  168   80   75   70  80  75  Javascript
4번    김수찬  없음  187   40   60   70  75  80          없음
5번    김재욱  없음  188   15   20   10  35  10          없음
6번    박동현  없음  202   80  100   95  85  80           C
7번    박혜정  없음  188   55   65   45  40  35      PYTHON
8번    승근열  없음  190  100   85   90  95  95          C#

In [66]:
df = pd.read_excel('file/score.xlsx',index_col='지원번호')

In [67]:


df['학교'] = np.nan 
df['학교'] = df['학교'].astype('object')
df

       이름   학교    키   국어   영어   수학  과학  사회        SW특기
지원번호
1번    강나래  NaN  197   90   85  100  95  85      Python
2번    강태원  NaN  184   40   35   50  55  25        Java
3번    강호림  NaN  168   80   75   70  80  75  Javascript
4번    김수찬  NaN  187   40   60   70  75  80         NaN
5번    김재욱  NaN  188   15   20   10  35  10         NaN
6번    박동현  NaN  202   80  100   95  85  80           C
7번    박혜정  NaN  188   55   65   45  40  35      PYTHON
8번    승근열  NaN  190  100   85   90  95  95          C#

In [65]:
# dropna : NaN데이터 삭제
# df.dropna(inplace=True) # nan데이터가 있는 모든 row삭제
# axis = index-rows 가로삭제, columns-column세로삭제 / how:any : 1개만 있어도 삭제, all:모두있어야 삭제
# df.dropna(axis='index',how='any') # 4,5번 삭제
# df.dropna(axis='index',how='all')  # 삭제 안됨, 모두 nan이어야 삭제
# df.dropna(axis='columns',how='all') # 삭제 안됨, 모두 nan이어야 삭제
# df.dropna(axis='columns',how='any') # SW특기 삭제
df.dropna(axis='1',how='all',inplace=True) # 삭제 안됨, 모두 nan이어야 삭제

ValueError: No axis named 1 for object type DataFrame