In [1]:
import pandas as pd

df =pd.read_excel('file/score.xlsx',index_col='지원번호')

In [ ]:
# df.columns 컬럼리스트
df.columns
# df['컬럼이름']
df['이름']
# df[['컬럼이름','컬럼이름']]: 2개 이상일때는 []리스트형태로
df[['이름','수학']]
# df['이름':'과학'] # 슬라이싱 안됨
df[df.columns[0:4]] # columns를 사용해서 슬라이싱 적용
df.loc[:,'이름':'국어'] # loc 를 사용해서 슬라이싱
df[0:3] # index에 해당되는 3개 출력
df.iloc[0:3]  # index에 해당되는 3개 출력

df[df.columns[-1]] # 마지막 컬럼 출력
df[df.columns[[0,3,-1]]]

       이름   학교    키  국어  영어   수학  과학  사회        SW특기
지원번호
1번    강나래  구로고  197  90  85  100  95  85      Python
2번    강태원  구로고  184  40  35   50  55  25        Java
3번    강호림  구로고  168  80  75   70  80  75  Javascript

In [ ]:
# loc 출력 - index 출력
# loc [[index이름:],[컬럼이름:]]
df.loc['1번']
df.loc[['1번','2번']]
df.loc['1번':'5번']
df.loc['1번','이름':'수학'] # 슬라이싱
df.loc['1번':'5번','이름':'수학'] # 슬라이싱
df.loc[['1번','5번'],'이름':'수학'] # 슬라이싱

       이름   학교    키  국어  영어   수학
지원번호
1번    강나래  구로고  197  90  85  100
2번    강태원  구로고  184  40  35   50
3번    강호림  구로고  168  80  75   70
4번    김수찬  구로고  187  40  60   70
5번    김재욱  구로고  188  15  20   10

In [26]:
# iloc 출력 - 리스트 번호로 출력
df.iloc[0]
df.iloc[0:4]
df.iloc[[0,1,4]]
df.iloc[0:4,1:5]
df.iloc[[0,4],1:5]

       학교    키  국어  영어
지원번호
1번    구로고  197  90  85
5번    구로고  188  15  20

In [35]:
# 조건 : True, False 
# df['키']>=185
df[df['키']>=185]['키']
df[df['키']>=80]['학교']

지원번호
1번     구로고
2번     구로고
3번     구로고
4번     구로고
5번     구로고
6번    디지털고
7번    디지털고
8번    디지털고
Name: 학교, dtype: str

In [ ]:
#df.loc[(index)row]
df.loc[df['키']>190, '학교':'과학']

        학교    키  국어   영어   수학  과학
지원번호
1번     구로고  197  90   85  100  95
6번    디지털고  202  80  100   95  85

In [39]:
df.loc[(df['키']>=185)&(df['학교']=='디지털고')]
df.loc[(df['키']>=185)|(df['학교']=='디지털고')]
df.loc[(df['국어']>85)|(df['수학']>=90)]

       이름    학교    키   국어   영어   수학  과학  사회    SW특기
지원번호
1번    강나래   구로고  197   90   85  100  95  85  Python
6번    박동현  디지털고  202   80  100   95  85  80       C
8번    승근열  디지털고  190  100   85   90  95  95      C#