In [2]:
import pandas as pd

df = pd.read_excel('file/score.xlsx',index_col='지원번호')
df

       이름    학교    키   국어   영어   수학  과학  사회        SW특기
지원번호
1번    강나래   구로고  197   90   85  100  95  85      Python
2번    강태원   구로고  184   40   35   50  55  25        Java
3번    강호림   구로고  168   80   75   70  80  75  Javascript
4번    김수찬   구로고  187   40   60   70  75  80         NaN
5번    김재욱   구로고  188   15   20   10  35  10         NaN
6번    박동현  디지털고  202   80  100   95  85  80           C
7번    박혜정  디지털고  188   55   65   45  40  35      PYTHON
8번    승근열  디지털고  190  100   85   90  95  95          C#

In [29]:
import pandas as pd
df = pd.read_csv('file/jumin08_2.csv',index_col='행정구역')
# df2 = df[['2026년08월_총인구수','2026년08월_세대수']]
# df2=df2['2026년08월_총인구수'].str.replace(',','').astype(int)

In [30]:
# df2.info()
# df2.sort_values('2026년08월_총인구수')
df['2026년08월_총인구수'] = df['2026년08월_총인구수'].str.replace(',','').astype(int)
df

,2026년08월_총인구수,2026년08월_세대수,2026년08월_세대당 인구,2026년08월_남자 인구수,2026년08월_여자 인구수,2026년08월_남여 비율
행정구역,,,,,,
전국 (1000000000),51084159,"24,505,258",2.08,"25,412,088","25,672,071",0.99
서울특별시 (1100000000),9281625,"4,525,061",2.05,"4,466,290","4,815,335",0.93
전남광주통합특별시 (1200000000),3155803,"1,579,291",2.00,"1,578,180","1,577,623",1.00
부산광역시 (2600000000),3229467,"1,583,256",2.04,"1,568,318","1,661,149",0.94
대구광역시 (2700000000),2346277,"1,123,265",2.09,"1,148,130","1,198,147",0.96
인천광역시 (2800000000),3066185,"1,418,345",2.16,"1,530,650","1,535,535",1.00
대전광역시 (3000000000),1442838,"706,437",2.04,"718,413","724,425",0.99
울산광역시 (3100000000),1086373,"502,387",2.16,"560,121","526,252",1.06
세종특별자치시 (3600000000),390738,"165,930",2.35,"194,589","196,149",0.99
경기도 (4100000000),13773918,"6,189,087",2.23,"6,914,277","6,859,641",1.01
강원특별자치도 (5100000000),1506662,"775,882",1.94,"757,981","748,681",1.01
충청북도 (4300000000),1601367,"808,665",1.98,"816,717","784,650",1.04
충청남도 (4400000000),2138938,"1,072,860",1.99,"1,098,834","1,040,104",1.06
전북특별자치도 (5200000000),1716965,"874,337",1.96,"855,796","861,169",0.99
경상북도 (4700000000),2492677,"1,303,782",1.91,"1,262,786","1,229,891",1.03
경상남도 (4800000000),3191645,"1,558,906",2.05,"1,609,943","1,581,702",1.02
제주특별자치도 (5000000000),662681,"317,767",2.09,"331,063","331,618",1.00

In [16]:
df = pd.read_csv('file/jumin08_2.csv',index_col='행정구역')

In [31]:
# 행정구역으로 역순정렬
df.sort_values('2026년08월_총인구수')

,2026년08월_총인구수,2026년08월_세대수,2026년08월_세대당 인구,2026년08월_남자 인구수,2026년08월_여자 인구수,2026년08월_남여 비율
행정구역,,,,,,
세종특별자치시 (3600000000),390738,"165,930",2.35,"194,589","196,149",0.99
제주특별자치도 (5000000000),662681,"317,767",2.09,"331,063","331,618",1.00
울산광역시 (3100000000),1086373,"502,387",2.16,"560,121","526,252",1.06
대전광역시 (3000000000),1442838,"706,437",2.04,"718,413","724,425",0.99
강원특별자치도 (5100000000),1506662,"775,882",1.94,"757,981","748,681",1.01
충청북도 (4300000000),1601367,"808,665",1.98,"816,717","784,650",1.04
전북특별자치도 (5200000000),1716965,"874,337",1.96,"855,796","861,169",0.99
충청남도 (4400000000),2138938,"1,072,860",1.99,"1,098,834","1,040,104",1.06
대구광역시 (2700000000),2346277,"1,123,265",2.09,"1,148,130","1,198,147",0.96
경상북도 (4700000000),2492677,"1,303,782",1.91,"1,262,786","1,229,891",1.03
인천광역시 (2800000000),3066185,"1,418,345",2.16,"1,530,650","1,535,535",1.00
전남광주통합특별시 (1200000000),3155803,"1,579,291",2.00,"1,578,180","1,577,623",1.00
경상남도 (4800000000),3191645,"1,558,906",2.05,"1,609,943","1,581,702",1.02
부산광역시 (2600000000),3229467,"1,583,256",2.04,"1,568,318","1,661,149",0.94
서울특별시 (1100000000),9281625,"4,525,061",2.05,"4,466,290","4,815,335",0.93
경기도 (4100000000),13773918,"6,189,087",2.23,"6,914,277","6,859,641",1.01
전국 (1000000000),51084159,"24,505,258",2.08,"25,412,088","25,672,071",0.99

In [37]:
df = pd.read_excel('file/students.xlsx',index_col='번호')
# 학교 순차정렬, 이름으로 역순정렬

# df.sort_values('학교')
# df.sort_values('이름',ascending=False).head(20)
df.sort_values(['학교','이름'],ascending=[True,False])

            이름   학교  학년    키  국어  영어  수학    SW특기
번호
68       Tresa  구로고   2  166  58  37  70    java
14     Sibylle  구로고   1  197  82  81  38    JAVA
63      Sarene  구로고   3  190  76  59  58  PYTHON
25       Robin  구로고   2  187  64  44  89  PYTHON
97        Nada  구로고   3  170  60  89  55  PYTHON
..         ...  ...  ..  ...  ..  ..  ..     ...
52        Buck  신림고   2  187  93  71  75       c
71       Booth  신림고   3  208  86  53  44  python
72       Beryl  신림고   3  171  82  26  55       C
53  Anthiathia  신림고   3  178  76   7  52  python
28       Alard  신림고   1  178  96   1  48

[100 rows x 8 columns]