In [24]:
import pandas as pd
df = pd.read_excel('file/score.xlsx',index_col='지원번호')

In [ ]:
df.describe()  # 기본적인 통계 정보
df.info()      # 각 컬럼과 인덱스의 있는 정보,타입,null값, 개수

<class 'pandas.DataFrame'>
Index: 8 entries, 1번 to 8번
Data columns (total 9 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   이름      8 non-null      str
 1   학교      8 non-null      str
 2   키       8 non-null      int64
 3   국어      8 non-null      int64
 4   영어      8 non-null      int64
 5   수학      8 non-null      int64
 6   과학      8 non-null      int64
 7   사회      8 non-null      int64
 8   SW특기    6 non-null      str
dtypes: int64(6), str(3)
memory usage: 940.0+ bytes

In [ ]:
df['국어'].max() # 최대값
df['국어'].min() # 최소값
df['국어'].mean() # 평균
df['국어'].count() # 개수
df['국어'].std() # 표준편처
# 세로출력
# df['국어']
# # 가로출력
# df.loc['5번']

np.float64(29.519969028245463)

In [25]:
# index 지정, 삭제
df.reset_index(drop=True ,inplace=True) # inplace를 해야 적용이 됨.
df.set_index('이름',inplace=True)
df

       학교    키   국어   영어   수학  과학  사회        SW특기
이름
강나래   구로고  197   90   85  100  95  85      Python
강태원   구로고  184   40   35   50  55  25        Java
강호림   구로고  168   80   75   70  80  75  Javascript
김수찬   구로고  187   40   60   70  75  80         NaN
김재욱   구로고  188   15   20   10  35  10         NaN
박동현  디지털고  202   80  100   95  85  80           C
박혜정  디지털고  188   55   65   45  40  35      PYTHON
승근열  디지털고  190  100   85   90  95  95          C#

In [26]:

df.sort_index(ascending=True) # True순차정렬 False역순정렬
df

       학교    키   국어   영어   수학  과학  사회        SW특기
이름
강나래   구로고  197   90   85  100  95  85      Python
강태원   구로고  184   40   35   50  55  25        Java
강호림   구로고  168   80   75   70  80  75  Javascript
김수찬   구로고  187   40   60   70  75  80         NaN
김재욱   구로고  188   15   20   10  35  10         NaN
박동현  디지털고  202   80  100   95  85  80           C
박혜정  디지털고  188   55   65   45  40  35      PYTHON
승근열  디지털고  190  100   85   90  95  95          C#