In [ ]:
import pandas as pd
df = pd.read_excel('file/score.xlsx',index_col='지원번호')

       이름    학교    키   국어   영어   수학  과학  사회        SW특기
지원번호
1번    강나래   구로고  197   90   85  100  95  85      Python
2번    강태원   구로고  184   40   35   50  55  25        Java
3번    강호림   구로고  168   80   75   70  80  75  Javascript
4번    김수찬   구로고  187   40   60   70  75  80         NaN
5번    김재욱   구로고  188   15   20   10  35  10         NaN
6번    박동현  디지털고  202   80  100   95  85  80           C
7번    박혜정  디지털고  188   55   65   45  40  35      PYTHON
8번    승근열  디지털고  190  100   85   90  95  95          C#

In [7]:
# 컬럼전체 이름변경
# df['학교'] = df['학교']+'등학교"
# df.replace({'고':'고등학교'},inplace=True)
# df['학교'] =df['학교'].str.replace({'고':'고등학교'})

In [ ]:
# 키 +cm 추가
# df['키'] =df['키'] +'cm' # 에러남 int와 str 문자열이 서로 다름 타입이 다름
# df['키'] = df['키'] +100 # 같은 int는 됨 같은 문자열 타입은 된다
# 타입이 다른경우 타입 변경후 적용
df['키']=df['키'].astype(str) +'cm' # str타입으로 변환 후 적용

       이름    학교      키   국어   영어   수학  과학  사회        SW특기
지원번호
1번    강나래   구로고  197cm   90   85  100  95  85      Python
2번    강태원   구로고  184cm   40   35   50  55  25        Java
3번    강호림   구로고  168cm   80   75   70  80  75  Javascript
4번    김수찬   구로고  187cm   40   60   70  75  80         NaN
5번    김재욱   구로고  188cm   15   20   10  35  10         NaN
6번    박동현  디지털고  202cm   80  100   95  85  80           C
7번    박혜정  디지털고  188cm   55   65   45  40  35      PYTHON
8번    승근열  디지털고  190cm  100   85   90  95  95          C#

In [27]:
# 함수 적용 : apply() - 컬럼 전체에 적용
def add_cm(h):
    return str(h)+'센티미터'

df['키'] = df['키'].apply(add_cm)

In [ ]:
# 함수적용
def capChange(lang):
    if pd.notnull(lang):
        return lang.lower()
    else: return '특기없음'

df['SW특기']=df['SW특기'].apply(capChange)


# df['SW특기'].str.lower()

       이름    학교    키   국어   영어   수학  과학  사회        SW특기
지원번호
1번    강나래   구로고  197   90   85  100  95  85      python
2번    강태원   구로고  184   40   35   50  55  25        java
3번    강호림   구로고  168   80   75   70  80  75  javascript
4번    김수찬   구로고  187   40   60   70  75  80        특기없음
5번    김재욱   구로고  188   15   20   10  35  10        특기없음
6번    박동현  디지털고  202   80  100   95  85  80           c
7번    박혜정  디지털고  188   55   65   45  40  35      python
8번    승근열  디지털고  190  100   85   90  95  95          c#

In [ ]:
# 1. 합계 : 과목 총점을 계산에서 컬럼 추가
# 2. 평균 컬럼을 추가
# 3. 등급 컬럼을 추가해서 90점 이상A, 80이상 B,70이상C,60이상D 그외 f를 입력
# 3번은 함수를 사용할것
def grade(avg):
    if avg>=90 :
        return 'A'
    elif avg>=80 :
        return 'B'
    elif avg>=70 :
        return 'C'
    elif avg>=60 :
        return 'D'
    else: return 'F'

df['합계'] = df['국어']+df['영어']+df['수학']+df['과학']+df['사회']
df['평균'] = df['합계']/5
df['등급'] = df['평균'].apply(grade)
df

       이름    학교    키   국어   영어   수학  과학  사회        SW특기   합계    평균 등급
지원번호
1번    강나래   구로고  197   90   85  100  95  85      Python  455  91.0  A
2번    강태원   구로고  184   40   35   50  55  25        Java  205  41.0  F
3번    강호림   구로고  168   80   75   70  80  75  Javascript  380  76.0  C
4번    김수찬   구로고  187   40   60   70  75  80         NaN  325  65.0  D
5번    김재욱   구로고  188   15   20   10  35  10         NaN   90  18.0  F
6번    박동현  디지털고  202   80  100   95  85  80           C  440  88.0  B
7번    박혜정  디지털고  188   55   65   45  40  35      PYTHON  240  48.0  F
8번    승근열  디지털고  190  100   85   90  95  95          C#  465  93.0  A