In [57]:
import pandas as pd
data = {
    '영화' : ['명량', '극한직업', '신과함께-죄와 벌', '국제시장', '괴물', '도둑들', '7번방의 선물', '암살'],
    '개봉 연도' : [2014, 2019, 2017, 2014, 2006, 2012, 2013, 2015],
    '관객 수' : [1761, 1626, 1441, 1426, 1301, 1298, 1281, 1270], # (단위 : 만 명)
    '평점' : [8.88, 9.20, 8.73, 9.16, 8.62, 7.64, 8.83, 9.10]
}
df = pd.DataFrame(data)
df

          영화  개봉 연도  관객 수    평점
0         명량   2014  1761  8.88
1       극한직업   2019  1626  9.20
2  신과함께-죄와 벌   2017  1441  8.73
3       국제시장   2014  1426  9.16
4         괴물   2006  1301  8.62
5        도둑들   2012  1298  7.64
6    7번방의 선물   2013  1281  8.83
7         암살   2015  1270  9.10

In [59]:
# 관객수 상위 5개만 출력
# def cal_change(x):
#     return f"{x:,}"
# df['관객 수'] =df['관객 수'].apply(cal_change)


# df['관객 수'] = df['관객 수'].apply(lambda x:f"{x:,}")

df['관객 수'] = df['관객 수'].map("{:,}".format)
df
df['관객 수']=df['관객 수'].sort_values(ascending=False).head(5)
df['관객 수'].astype(str)
df['관객 수']=df['관객 수']+'만명'
df

ValueError: Cannot specify ',' with 's'.

In [60]:
# 1. 함수사용 - 천단위 표시
def cal_change(x):
    return  f"{x:,}"
    # return  '{:,d}'.format() # 숫자를 문자변형

df['관객 수'] = df['관객 수'].apply(cal_change)

#  2. lambda함수적용
df['관객 수'] = df['관객 수'].apply(lambda x: f"{x:,}")
#  3. map사용
# df['관객 수'] = df['관객 수'].map('{:,}'.format)

ValueError: Cannot specify ',' with 's'.

In [74]:
data = {
    '영화' : ['명량', '극한직업', '신과함께-죄와 벌', '국제시장', '괴물', '도둑들', '7번방의 선물', '암살'],
    '개봉 연도' : [2014, 2019, 2017, 2014, 2006, 2012, 2013, 2015],
    '관객 수' : [1761, 1626, 1441, 1426, 1301, 1298, 1281, 1270], # (단위 : 만 명)
    '평점' : [8.88, 9.20, 8.73, 9.16, 8.62, 7.64, 8.83, 9.10]
}

df = pd.DataFrame(data)

In [76]:
# 개봉연도 내림차순, 오름차순으로 출력
#1
# df['개봉 연도'].sort_values(ascending=False)
# df['개봉 연도'].sort_values(ascending=True)

# 평점이 9점 이상만 출력
df[df['평점']>=9.0]
df
# 평점 컬럼 내용에 8.88(점) 글자를 넣어서 출력
# 평점중 평점 평균 이상인 row만 출력
# 2015년 이후에 개봉한 영화 출력


#2

          영화  개봉 연도  관객 수     평점
0         명량   2014  1761  False
1       극한직업   2019  1626   True
2  신과함께-죄와 벌   2017  1441  False
3       국제시장   2014  1426   True
4         괴물   2006  1301  False
5        도둑들   2012  1298  False
6    7번방의 선물   2013  1281  False
7         암살   2015  1270   True