In [34]:
import pandas as pd
df = pd.read_excel('file/score.xlsx',index_col='지원번호')

In [35]:
import random
df['요일'] = 0
# list = [0,1,2,3,4,5,6]
for i in range(8):
    df.iloc[i,9] = random.randint(0,6)


df

       이름    학교    키   국어   영어   수학  과학  사회        SW특기  요일
지원번호
1번    강나래   구로고  197   90   85  100  95  85      Python   6
2번    강태원   구로고  184   40   35   50  55  25        Java   2
3번    강호림   구로고  168   80   75   70  80  75  Javascript   0
4번    김수찬   구로고  187   40   60   70  75  80         NaN   4
5번    김재욱   구로고  188   15   20   10  35  10         NaN   4
6번    박동현  디지털고  202   80  100   95  85  80           C   3
7번    박혜정  디지털고  188   55   65   45  40  35      PYTHON   4
8번    승근열  디지털고  190  100   85   90  95  95          C#   2

In [38]:
# 0-일 1-월 2-화 3-수 4-목 5-금 6-토
# 출력하시오
def today(a):
    if a == 0:
        return "일요일"
    elif a == 1:
        return "월요일"
    elif a == 2:
        return "화요일"
    elif a == 3:
        return "수요일"
    elif a == 4:
        return "목요일"
    elif a == 5:
        return "금요일"
    elif a == 6:
        return "토요일"
df['요일']=df['요일'].apply(today)
df

       이름    학교    키   국어   영어   수학  과학  사회        SW특기    요일
지원번호
1번    강나래   구로고  197   90   85  100  95  85      Python  None
2번    강태원   구로고  184   40   35   50  55  25        Java  None
3번    강호림   구로고  168   80   75   70  80  75  Javascript  None
4번    김수찬   구로고  187   40   60   70  75  80         NaN  None
5번    김재욱   구로고  188   15   20   10  35  10         NaN  None
6번    박동현  디지털고  202   80  100   95  85  80           C  None
7번    박혜정  디지털고  188   55   65   45  40  35      PYTHON  None
8번    승근열  디지털고  190  100   85   90  95  95          C#  None

In [60]:
data = {
    '번호':['1번','2번','3번','4번','5번','6번','7번','8번'],
    '이름':['홍길동','유관순','이순신','강감찬','김구','김유신','홍길자','홍길순'],
    '달러':['$19,700','$18,400','$16,800','$18,700','$18,800','$20,200','$18,800','$19,000'],
    '우대':[90,40,80,40,15,80,55,100]
}
df = pd.DataFrame(data)
df.set_index('번호',inplace=True)
df

     이름       달러   우대
번호
1번  홍길동  $19,700   90
2번  유관순  $18,400   40
3번  이순신  $16,800   80
4번  강감찬  $18,700   40
5번   김구  $18,800   15
6번  김유신  $20,200   80
7번  홍길자  $18,800   55
8번  홍길순  $19,000  100

In [ ]:
# 1 금액컬럼을 추가하시오 (금액:달러+(달러*달러우대*0.01))
# 2 우대가 50 이상인 사람에게만 달러+달러*우대*0.01
#50 미만은 달러만 입력

# 우대 50 이상인 사람에게 달러+달러X우대X0.01
# 우대가 50미만 달러

df['달러']=df['달러'].str.replace({'$':'', ',':''}).astype(int)
def cal_dal(a):
    if a >=50:
        return a
    else:
        return 0
df['우대']=df['우대'].apply(cal_dal)
df['금액'] = df['달러']+(df['달러']*df['우대']*0.01)

df

     이름     달러   우대       금액
번호
1번  홍길동  19700   90  37430.0
2번  유관순  18400    0  18400.0
3번  이순신  16800   80  30240.0
4번  강감찬  18700    0  18700.0
5번   김구  18800    0  18800.0
6번  김유신  20200   80  36360.0
7번  홍길자  18800   55  29140.0
8번  홍길순  19000  100  38000.0