In [80]:
import pandas as pd

df = pd.read_excel('file/score.xlsx',index_col='지원번호')

In [81]:
# 합계,평균,결과 컬럼 추가
# 결과 평균점수가 70점 이상은 합격, 불합격으로 출력
df['합계'] =df['국어']+df['영어']+df['수학']
df['평균'] =df['합계']/3
df['결과'] = "불합격"
df.loc[df['평균']>=70, '결과'] = '합격'

In [20]:
# df.value_counts('결과') # 그룹으로 개수 확인

In [27]:
# df2 = df[['이름','평균','결과']]
# df2
df[df.columns[0:3]]

            이름    학교  학년
번호
1      Eadmund   신림고   2
2       Kirbee   구로고   1
3    Appolonia   구로고   3
4        Avery   구로고   2
5       Dallis  디지털고   1
..         ...   ...  ..
96        Luke   신림고   3
97        Nada   구로고   3
98       Fiona   신림고   1
99        Leif   구로고   2
100   Jonathan  디지털고   2

[100 rows x 3 columns]

In [35]:
a_list=[1,2,3,4,5]
b_list=[4,5,6]
c = a_list+b_list
c

[1, 2, 3, 4, 5, 4, 5, 6]

In [ ]:
# cols리스트 순서를 변경
# 1. 리스트타입으로 변경
cols= list(df.columns) # 리스트 타입으로 변경후 순서를 변경


cols[-2:] # 평균,결과 컬럼
cols[:-2] # 이름~합계 컬럼
cols[0] # 이름
type(cols[:-2]) # list
type(cols[0]) # str


# 2. 리스트 순서를 변경
cols=[cols[0]]+cols[-2:]+cols[:-2] # str+list+list 0>error, 그래서 str을 []list로 변환해야함

# 3.변경된 리스트 적용
df=df[cols]
df

,이름,평균,결과,이름,학교,학년,키,국어,영어,수학,SW특기,합계
번호,,,,,,,,,,,,
1,Eadmund,69.333333,불합격,Eadmund,신림고,2,171,56,92,60,c,208
2,Kirbee,36.000000,불합격,Kirbee,구로고,1,199,53,10,45,C,108
3,Appolonia,70.000000,합격,Appolonia,구로고,3,193,77,52,81,C,210
4,Avery,45.666667,불합격,Avery,구로고,2,187,59,35,43,C,137
5,Dallis,76.666667,합격,Dallis,디지털고,1,209,97,57,76,C,230
...,...,...,...,...,...,...,...,...,...,...,...,...
96,Luke,71.000000,합격,Luke,신림고,3,187,91,63,59,Python,213
97,Nada,68.000000,불합격,Nada,구로고,3,170,60,89,55,PYTHON,204
98,Fiona,92.000000,합격,Fiona,신림고,1,200,97,95,84,C,276
99,Leif,71.333333,합격,Leif,구로고,2,192,96,84,34,PYTHON,214
100,Jonathan,75.666667,합격,Jonathan,디지털고,2,195,84,63,80,JAVA,227

In [46]:
# 컬럼수정 : replace(), 존재하는 컬럼에 값을 입력하면 수정됨
# 컬럼추가 : 없는 컬럼에 값을 입력하면 추가됨
# 컬럼삭제 : drop()형태를 사용 여러개 삭제 가능,inplace=True 적용해야함( del은 1개만 삭제됨.)

In [98]:
# row : index 수정 추가 삭제
# index 삭제 - 조건 사용해서 삭제
# 수학 점수가 80점 미만 학생 삭제

filt = df['수학']>=80
# df[~filt].count()
# df2 = df[~filt]
# df2

# # column삭제
# df.drop(columns=['평균','결과'],inplace=True) 

# index row삭제
# df.drop(index=['1번','2번'],inplace=True) 

# 2. 조건을 이용한 index삭제
# filt.index
df.drop(index=df[~filt].index,inplace=True) 
df

       이름    학교    키   국어   영어   수학  과학  사회    SW특기
지원번호
1번    강나래   구로고  197   90   85  100  95  85  Python
6번    박동현  디지털고  202   80  100   95  85  80       C
8번    승근열  디지털고  190  100   85   90  95  95      C#

In [4]:
import pandas as pd

df = pd.read_excel('file/score.xlsx',index_col='지원번호')
df

       이름    학교    키   국어   영어   수학  과학  사회        SW특기
지원번호
1번    강나래   구로고  197   90   85  100  95  85      Python
2번    강태원   구로고  184   40   35   50  55  25        Java
3번    강호림   구로고  168   80   75   70  80  75  Javascript
4번    김수찬   구로고  187   40   60   70  75  80         NaN
5번    김재욱   구로고  188   15   20   10  35  10         NaN
6번    박동현  디지털고  202   80  100   95  85  80           C
7번    박혜정  디지털고  188   55   65   45  40  35      PYTHON
8번    승근열  디지털고  190  100   85   90  95  95          C#

In [107]:
df.columns
# 국어 영어 수학 과학 사회 점수 합계컬럼을 추가
# 합계점수가 350점 이상만 출력
# 350점 미만 삭제후 출력
df['합계'] = df['국어']+df['영어']+df['수학']+df['과학']+df['사회']
filt = df['합계']>=350
# df[filt]


df.drop(index=df[~filt].index,inplace=True)

df

       이름    학교    키   국어   영어   수학  과학  사회        SW특기   합계
지원번호
1번    강나래   구로고  197   90   85  100  95  85      Python  455
3번    강호림   구로고  168   80   75   70  80  75  Javascript  380
6번    박동현  디지털고  202   80  100   95  85  80           C  440
8번    승근열  디지털고  190  100   85   90  95  95          C#  465

In [121]:
#index 추가 : loc[]를 이용, 컬럼 개수만큼 입력
# df.loc['9번'] = ['홍길동','구로고',190,80,70,90,50,60,'Python']

# 값 추가
# df.loc["4번",'SW특기'] = 'C'

# 부분 수정
# df.loc["4번",['학교','SW특기']] = '포켓몬고','C'
# df.loc["5번",['학교','사회','SW특기']] = '디지털고',40,'Java'
df

       이름    학교    키   국어   영어   수학  과학  사회        SW특기
지원번호
1번    강나래   구로고  197   90   85  100  95  85      Python
2번    강태원   구로고  184   40   35   50  55  25        Java
3번    강호림   구로고  168   80   75   70  80  75  Javascript
4번    김수찬  포켓몬고  187   40   60   70  75  80           C
5번    김재욱  디지털고  188   15   20   10  35  40        Java
6번    박동현  디지털고  202   80  100   95  85  80           C
7번    박혜정  디지털고  188   55   65   45  40  35      PYTHON
8번    승근열  디지털고  190  100   85   90  95  95          C#
9번    홍길동   구로고  190   80   70   90  50  60      Python

In [125]:
df.loc['4번','이름'] = '홍길순'
df['영어'] = 0
df['체육'] =100
df

       이름    학교    키   국어  영어   수학  과학  사회        SW특기   체육
지원번호
1번    강나래   구로고  197   90   0  100  95  85      Python  100
2번    강태원   구로고  184   40   0   50  55  25        Java  100
3번    강호림   구로고  168   80   0   70  80  75  Javascript  100
4번    홍길순  포켓몬고  187   40   0   70  75  80           C  100
5번    김재욱  디지털고  188   15   0   10  35  40        Java  100
6번    박동현  디지털고  202   80   0   95  85  80           C  100
7번    박혜정  디지털고  188   55   0   45  40  35      PYTHON  100
8번    승근열  디지털고  190  100   0   90  95  95          C#  100
9번    홍길동   구로고  190   80   0   90  50  60      Python  100

In [5]:
# 컬럼 이름 변경
# # df.columns = [변경할 이름 입력]
# df2 = df[['이름','국어','영어']]
# df2.columns = ['name',"kor",'eng'] # 컬럼명 변경
# df2

# 부분 컬럼이름 변경 : rename
# df. rename(columns={'이름':'name', '국어':'kor', '영어':'eng'}, inplace= True)
# df

# df.columns[1] = 'school' 이경우는 에러남
df.rename(columns={'학교': 'school'}, inplace=True)
df

       이름 school    키   국어   영어   수학  과학  사회        SW특기
지원번호
1번    강나래    구로고  197   90   85  100  95  85      Python
2번    강태원    구로고  184   40   35   50  55  25        Java
3번    강호림    구로고  168   80   75   70  80  75  Javascript
4번    김수찬    구로고  187   40   60   70  75  80         NaN
5번    김재욱    구로고  188   15   20   10  35  10         NaN
6번    박동현   디지털고  202   80  100   95  85  80           C
7번    박혜정   디지털고  188   55   65   45  40  35      PYTHON
8번    승근열   디지털고  190  100   85   90  95  95          C#